### ISSUE TITLE
write tests for identity2.js

### ISSUE THREAD

**Issue by abhiShandy** [WiiQare/frontend#133]
Refer https://app.codecov.io/gh/WiiQare/frontend/blob/main/components%2Fatoms%2FStepper%2FForms%2Fidentity2.js

**Comment by ShatilKhan** [comment]
I'd like to take on this issue. Please assign me.
It would be great if any test writing guidelines were provided

**Comment by abhiShandy** [comment]
@ShatilKhan Checkout the existing text file

https://github.com/WiiQare/frontend/blob/main/components/atoms/Stepper/Forms/identity.test.js

It includes a tests for happy path. You can start testing loading and error states.
